### ISSUE TITLE
Convert large GeoJSON file to PMTiles 

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/networkmerge#58]
Here is the link: https://github.com/nptscot/networkmerge/releases/download/v0.1/large_exmaple_merged.geojson

**Comment by mem48** [comment]
@wangzhao0217 a few observations on the output

1) Each feature has an unnneeded identifier e.g. `643A0F6B-543E-4058-AB9B-D623D2767D96` which adds a lot to the file size
2) Each feature has XYZ coordinates (but the z coodiate is always 0
3) The coordinates are over precise `-5.696953159326259, 55.310563537520999` is atomic precision (see https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude )

**Comment by wangzhao0217** [comment]
> @wangzhao0217 a few observations on the output
> 
> 1. Each feature has an unnecessary identifier e.g. `643A0F6B-543E-4058-AB9B-D623D2767D96`, which adds a lot to the file size
> 2. Each feature has XYZ coordinates (but the z coordinate is always 0
> 3. The coordinates are over precise `-5.696953159326259, 55.310563537520999` is atomic precision (see https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude )

Thank you, Malcolm, I will make the changes accordingly

**Comment by mem48** [comment]
Also, an extra length_x variable is included and the results appear to cover every road in Scotland, even if there's no cycling potential. This massively adds to the file size.

**Comment by mem48** [comment]
I've added a simplified toggle to the website.

![image](https://github.com/nptscot/networkmerge/assets/15819577/2d7d1297-d070-4e81-b0af-880e0b1ffea3)

The schools doesn't work due to the new file not having separate primary/secondary networks. The bike network also appears to be missing.


Some examples to debug 

Side roads with different values
https://nptscot.github.io/#18.22/55.949209/-3.204828
https://nptscot.github.io/#17.42/55.951919/-3.201154


A simplified network has less flow than the full network
https://nptscot.github.io/#18.24/55.947264/-3.176876
https://nptscot.github.io/#18.57/55.9572347/-3.1452956


Simplified network missing
https://nptscot.github.io/#17.33/55.964982/-3.166303
https://nptscot.github.io/#16.42/55.952579/-3.104297

**Comment by mem48** [comment]
Results are really patchy for the quiet network

**Comment by mem48** [comment]
https://github.com/nptscot/outputdata/releases/download/v2023-09-09/combined_network_tile.zip

**Comment by Robinlovelace** [comment]
Great stuff. @wangzhao0217 can you try to:

- [ ] Re-join for a small random sample across Scotland, using the new `crs = "EPSG:27700"` argument of `rnet_merge()`
- [ ] Check to see if merge is better in places far from the centre of Scotland (hypothesis: yes)
- [ ] Remove the identifier
- [ ] Share the updated GeoJSON for tiling

In terms of re-building the national network, I'm thinking about how to speed-up the process. As a bonus, you could take a look at and try to fix this: https://github.com/ropensci/stplanr/issues/522

**Comment by Robinlovelace** [comment]
Closing in favour of https://github.com/nptscot/npt/issues/291

**Comment by Robinlovelace** [comment]
Let's keep this repo for discussion of the general methods and paper in collaboration others, and the nptscot/npt repo for the application of the method for the specific project is my thinking.

**Comment by Robinlovelace** [comment]
Also: the GeoJSON has been converted :tada:

**Comment by mvl22** [comment]
New paper may be of interest:
https://x.com/martinfleis/status/1808954566966235263
