### ISSUE TITLE
Test on large network example

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#8]
I've uploaded a 300 MB file here: https://github.com/nptscot/networkmerge/releases/download/v0.1/large_route_network_example_edingurgh.geojson

**Comment by wangzhao0217** [comment]
Hi  @Robinlovelace @mem48 
Please find the simplified network here: https://github.com/nptscot/networkmerge/releases/download/v0.1/simplified_network_npt.geojson
It should simplify the network without losing details. Here is a good example:
_**was:**_
![image](https://github.com/nptscot/networkmerge/assets/74598734/602e2dcc-b214-4de3-b964-e2d00257daef)
![image](https://github.com/nptscot/networkmerge/assets/74598734/ec26f37f-61c0-4598-b695-66fbb63b8b85)
**_now:_**
![image](https://github.com/nptscot/networkmerge/assets/74598734/29d6af1b-35d1-405a-89af-1b34cdc27e59)

**Comment by Robinlovelace** [comment]
Looking good Zhao, great work! The method has been tested on a large network, so closing this issue. @mem48 can you try to get that .geojson file tiled and deployed on our web app, assuming it's good to go. From what I can tell it seems much better than what is there currently, putting it on our website may help further debug it and improve on the simplified network outputs.

**Comment by mem48** [comment]
I've put the latest version on the dev website.

Still see odd results on some side roads. But this may be because you're using an old version of the data.

E.g. 
https://nptscot.github.io/#18.21/55.944712/-3.197395 
https://nptscot.github.io/#15.73/55.938757/-3.158171
https://nptscot.github.io/#16.64/55.955197/-3.109993
https://nptscot.github.io/#16.5/56.021685/-3.406723

**Comment by Robinlovelace** [comment]
> I've put the latest version on the dev website.
> 
> Still see odd results on some side roads. But this may be because you're using an old version of the data.
> 
> E.g. https://nptscot.github.io/#18.21/55.944712/-3.197395 https://nptscot.github.io/#15.73/55.938757/-3.158171 https://nptscot.github.io/#16.64/55.955197/-3.109993 https://nptscot.github.io/#16.5/56.021685/-3.406723

Good stuff, yes probably because it's an old version of the data. @wangzhao0217 can you update the network ASAP so we can test on the latest version of the data?

**Comment by Robinlovelace** [comment]
Looking at https://nptscot.github.io/#15.64/55.956999/-3.105648 the simplified network has values that are too high on the parallel road. I suggest reducing the size of the buffer, e.g. to 20 or even 15 or 10 m.

![image](https://github.com/nptscot/networkmerge/assets/1825120/c94f9b9b-72dc-4c60-ab03-02760815b2b0)

**Comment by Robinlovelace** [comment]
Closing in favour of https://github.com/nptscot/npt/issues/291

We should focus on applying the method in the npt codebase and eventually integrate into the build.

**Comment by wangzhao0217** [comment]
https://nptscot.github.io/#18.21/55.944712/-3.197395
was:
[image: 9b624000-35ba-42bf-a83d-83873eb15625.png][image: image.png]
now:
[image: image.png]

   - sidewalk is ignored, but the values are correct within the same band.

------------------------------------------------------------------------------------------------------------------------------------------------
https://nptscot.github.io/#15.73/55.938757/-3.158171
was:
[image: image.png]
now:
[image: image.png]

   - this part is hard to solve. This road's winding caused low value. I
   tried to segment it into small lengths. This improved results for the road
   only, but affected others.

------------------------------------------------------------------------------------------------------------------------------------------------
https://nptscot.github.io/#16.64/55.955197/-3.109993
[image: image.png][image: 0dd7f8ea-e74f-4b83-a1c0-cced57b27ee8.png]

   - The rnet_merge works okay, the difference is caused by the original
   data, there are small pieces of the road hidden beneath the grey line.

------------------------------------------------------------------------------------------------------------------------------------------------
https://nptscot.github.io/#16.5/56.021685/-3.406723
was:
[image: image.png][image: image.png]
now:
[image: image.png]

   - values are in the correct band.
